In [48]:
class Neural_Net(object):
    """docstring for Neural_Net"""
    def __init__(self):
        # Defining Hyperparameters
        self.inputLayerSize 	= 2
        self.outputLayerSize 	= 1
        self.hiddenLayerSize 	= 3

        # Weights (parameters)
        self.w1 = np.random.randn(self.inputLayerSize, self.hiddenLayerSize)
        self.w2 = np.random.randn(self.hiddenLayerSize, self.outputLayerSize)

    def forward(self, X):
        #Propagate inputs through network

        self.z2 = np.dot(X, self.w1)
        self.a2 = self.sigmoid(self.z2)
        #print(self.a2)
        self.z3 = np.dot(self.a2, self.w2)
        #print(self.z3)
        yHat	= self.sigmoid(self.z3)
        return yHat

    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))


In [49]:
import numpy as np
import seaborn as sb

x = np.array(([3,5],[5, 1], [10, 2]), dtype=float)
y = np.array(([75],[82], [93]), dtype=float)

x = x/np.amax(x, axis=0)
y = y/100

NN = Neural_Net()
print(NN.forward(x))
print(NN.w1)
print(NN.w2)


[[ 0.40048469]
 [ 0.42808635]
 [ 0.3210797 ]]
[[ 0.70564026 -1.10003476 -0.99144728]
 [ 1.2706662   0.65255396 -0.20565581]]
[[-1.77468619]
 [ 0.94621753]
 [ 1.31110361]]


In [61]:
import time

weightsToTry = np.linspace(-10,10,1000)
cost = np.zeros((5000, 5000))


startTime = time.clock()

print("Training Please wait...")
for i in range(5000):
    for j in range(5000):
        #NN.w1[0,0] = weightsToTry[i]
        #NN.w1[0,1] = weightsToTry[j]
        NN.w1 = np.random.uniform(-10,10,[NN.inputLayerSize, NN.hiddenLayerSize]) # taking range of value with 2x3 size
        NN.w2 = np.random.uniform(-10,10,[NN.hiddenLayerSize, NN.outputLayerSize]) # taking range of value with 3x1 size
        yHat = NN.forward(x)
        cost[i,j] = 0.5*(sum(y-yHat)**2)

endTime = time.clock()
print(endTime - startTime)

print(np.amin(cost))
print(np.argmin(cost))

        

Training Please wait...
1157.8850813196314
5.74958824061e-16
10559392


In [66]:
NN.forward(x)

array([[ 0.02439153],
       [ 0.09939044],
       [ 0.10411611]])

In [58]:
print(cost[515,732])

8.51198517654e-15


In [63]:
print(NN.w1)

[[-3.18698992 -9.43518459  9.7433166 ]
 [-3.91034618  1.26647382  6.17634633]]


In [65]:
print(NN.w2)

[[ 0.56794313]
 [-8.88355134]
 [-2.15600359]]
